"""Using JSON, normal SQLALCHEMY too messy

Revision ID: 0461a8305ce2
Revises: 69d31dbb765b
Create Date: 2026-05-03 08:58:04.999915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0461a8305ce2'
down_revision = '69d31dbb765b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neuron')
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neurons', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.drop_column('neurons')

    op.create_table('neuron',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('layer_id', sa.INTEGER(), nullable=False),
    sa.Column('tt', sa.INTEGER(), nullable=True),
    sa.Column('w', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
