"""Adding w to Neuron Model

Revision ID: 113c0688d1b2
Revises: 49a02d4e552d
Create Date: 2026-05-02 11:40:35.676957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113c0688d1b2'
down_revision = '49a02d4e552d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('w', sa.JSON(), nullable=False))
        batch_op.drop_column('last_I')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_I', sa.FLOAT(), nullable=True))
        batch_op.drop_column('w')

    # ### end Alembic commands ###
