"""Using JSON, normal SQLALCHEMY too messy

Revision ID: 1a8d8169e71a
Revises: 0461a8305ce2
Create Date: 2026-05-03 08:58:47.530169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8d8169e71a'
down_revision = '0461a8305ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neurons', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.drop_column('neurons')

    # ### end Alembic commands ###
