"""empty message

Revision ID: 5952b0691c0f
Revises: 016db4a22876
Create Date: 2026-05-02 11:42:23.046416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5952b0691c0f'
down_revision = '016db4a22876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Neuron')
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('w', sa.JSON(), nullable=True))
        batch_op.drop_column('last_I')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_I', sa.FLOAT(), nullable=True))
        batch_op.drop_column('w')

    op.create_table('_alembic_tmp_Neuron',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('w', sqlite.JSON(), nullable=False),
    sa.Column('layer_id', sa.INTEGER(), nullable=False),
    sa.Column('tt', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
