"""empty message

Revision ID: 65f9aa64ff19
Revises: f8d91eec6244
Create Date: 2026-05-02 19:44:50.763402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '65f9aa64ff19'
down_revision = 'f8d91eec6244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neuron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('tt', sa.Integer(), nullable=True),
    sa.Column('w', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Neuron')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Neuron',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('layer_id', sa.INTEGER(), nullable=False),
    sa.Column('tt', sa.INTEGER(), nullable=True),
    sa.Column('w', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('neuron')
    # ### end Alembic commands ###
