"""Using JSON, normal SQLALCHEMY too messy

Revision ID: 7f64db364eb1
Revises: 1a8d8169e71a
Create Date: 2026-05-03 08:59:42.823952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f64db364eb1'
down_revision = '1a8d8169e71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neurons', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer', schema=None) as batch_op:
        batch_op.drop_column('neurons')

    # ### end Alembic commands ###
