"""empty message

Revision ID: 88e06220cf1c
Revises: c833a7040cd9
Create Date: 2026-05-02 12:12:42.032663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e06220cf1c'
down_revision = 'c833a7040cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_I', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.drop_column('last_I')

    # ### end Alembic commands ###
