"""New models

Revision ID: aab8c79bacfd
Revises: 88e06220cf1c
Create Date: 2026-05-02 17:33:35.667347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab8c79bacfd'
down_revision = '88e06220cf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.add_column(sa.Column('w', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Neuron', schema=None) as batch_op:
        batch_op.drop_column('w')

    # ### end Alembic commands ###
