"""empty message

Revision ID: c833a7040cd9
Revises: 5952b0691c0f
Create Date: 2026-05-02 11:59:36.574816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c833a7040cd9'
down_revision = '5952b0691c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['param_id'], ['Params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Neuron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('tt', sa.Integer(), nullable=True),
    sa.Column('w', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('pred_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['pred_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('pred_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edges')
    op.drop_table('Neuron')
    op.drop_table('layer')
    op.drop_table('Params')
    # ### end Alembic commands ###
