"""empty message

Revision ID: ddb35055c1c5
Revises: 4fb90d32c89e
Create Date: 2026-05-02 20:13:24.592665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb35055c1c5'
down_revision = '4fb90d32c89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['param_id'], ['params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('pred_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['pred_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('pred_id', 'post_id')
    )
    op.create_table('neuron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('tt', sa.Integer(), nullable=True),
    sa.Column('w', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neuron')
    op.drop_table('edges')
    op.drop_table('layer')
    op.drop_table('params')
    # ### end Alembic commands ###
